### ISSUE TITLE
Painfully slow with Standard Storage

### ISSUE THREAD

**Issue by colemickens** [theobolo/kube-registry-azure#2]
If I use a docker-registry with local storage on an Azure node with Standard storage, I can push my images in about 1 minute.

With this Azure Storage backed registry, I'm seeing pushes taking 8 minutes.

CC @ahmetalpbalkan in case you've seen this or can advise

**Comment by theobolo** [comment]
@colemickens  i'm closing this until the Premium Storage will able to be used as other usage than only Pages blobs (Disks)

**Comment by theobolo** [comment]
I updated the registry image to the Rc2 version it seems that the Speed with a standard Storage is a little bit better !

**Comment by ahmetalpbalkan** [comment]
@theobolo you mean docker registry v.2.5.0-rc.2? That sounds interesting. what were you using before?

**Comment by colemickens** [comment]
Last change to the `azure` driver was on March 21, well before rc1 or rc2. If there are material improvements, it's not from changes in Azure-specific code, as far as I can tell.

**Comment by ahmetalpbalkan** [comment]
It might be some upload parallelization or chunk size adjustment or something like that added in the registry code. I have no idea either. A good amount of the time is spent at round-trip requests for smaller files etc. If you're truly curious run registry container with `-e REGISTRY_DEBUG=1` and you will get duration traces about each call made into the storage driver.
